/* SACOG Region Pipeline Project Inventory — map app
 * Pure front-end. Consumes data/pipeline.geojson (generated by tools/export_geojson.py)
 * plus the overlays in data/overlays/ (generated by tools/build_overlays.py).
 * No API key required: dark basemap = CARTO raster tiles, glyphs = protomaps fonts.
 */

// ---- Color scheme (must match tools/export_geojson.py EXPLICIT_BUCKET) ----
const BUCKET_COLORS = {
  residential: "#ffd400", // housing only
  mixed:       "#b14bff", // housing + jobs
  nonres:      "#ff3b30", // jobs only
};
const BUCKET_LABELS = {
  residential: "Residential",
  mixed:       "Mixed use (housing + jobs)",
  nonres:      "Non-residential",
};

const DEFAULT_VIEW = { center: [-121.3, 38.72], zoom: 8.2 }; // SACOG region fallback

// ---- Basemap style: black background + dark raster tiles, no token ----
const style = {
  version: 8,
  glyphs: "https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf",
  sources: {
    "carto-dark": {
      type: "raster",
      tiles: [
        "https://a.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://b.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://c.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://d.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
      ],
      tileSize: 256,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
    },
  },
  layers: [
    { id: "bg", type: "background", paint: { "background-color": "#000000" } },
    { id: "carto-dark", type: "raster", source: "carto-dark", paint: { "raster-opacity": 0.82 } },
  ],
};

const map = new maplibregl.Map({
  container: "map",
  style,
  center: DEFAULT_VIEW.center,
  zoom: DEFAULT_VIEW.zoom,
  attributionControl: { compact: true },
});
map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");

function setStatus(msg) {
  let el = document.getElementById("status-msg");
  if (!msg) { if (el) el.remove(); return; }
  if (!el) {
    el = document.createElement("div");
    el.id = "status-msg";
    document.body.appendChild(el);
  }
  el.innerHTML = msg;
}

// ---- City + county boundaries (shown automatically) ----
function addBoundaries() {
  const url = "data/overlays/city_county_boundary.geojson";
  fetch(url, { cache: "no-cache" })
    .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
    .then((data) => {
      map.addSource("boundary", { type: "geojson", data });
      // County outlines — brighter. Counties have no CITY_NAME.
      map.addLayer({
        id: "boundary-county",
        type: "line",
        source: "boundary",
        filter: ["!", ["has", "CITY_NAME"]],
        paint: { "line-color": "#ffffff", "line-opacity": 0.34, "line-width": 1.3 },
      }, "projects-circles");
      // City outlines — dimmer, dashed.
      map.addLayer({
        id: "boundary-city",
        type: "line",
        source: "boundary",
        filter: ["has", "CITY_NAME"],
        paint: {
          "line-color": "#9fb4d0",
          "line-opacity": 0.32,
          "line-width": 0.8,
          "line-dasharray": [2, 2],
        },
      }, "projects-circles");
      // Faint county name labels for orientation (low zoom only).
      map.addLayer({
        id: "boundary-county-label",
        type: "symbol",
        source: "boundary",
        filter: ["!", ["has", "CITY_NAME"]],
        maxzoom: 10,
        layout: {
          "text-field": ["upcase", ["get", "COUNTY"]],
          "text-font": ["Noto Sans Regular"],
          "text-size": 11,
          "text-letter-spacing": 0.18,
          "symbol-placement": "point",
        },
        paint: {
          "text-color": "#7f8794",
          "text-halo-color": "#000000",
          "text-halo-width": 1.2,
        },
      }, "projects-circles");
    })
    .catch(() => { /* boundaries optional; ignore if absent */ });
}

// ---- Metrics panel ----
function fmt(n) { return Number(n).toLocaleString("en-US"); }

function renderMetrics(m) {
  if (!m) return;
  const top = (m.top_jurisdictions || [])
    .map((j) => {
      const pct = m.top_jurisdictions[0].units
        ? Math.round((j.units / m.top_jurisdictions[0].units) * 100)
        : 0;
      const name = j.name.replace(/^City of /, "").replace(/ County$/, " Co. (uninc.)");
      return `<div class="jrow">
          <div class="jbar" style="width:${pct}%"></div>
          <span class="jname">${esc(name)}</span>
          <span class="jval">${fmt(j.units)}</span>
        </div>`;
    })
    .join("");

  document.getElementById("metrics-body").innerHTML = `
    <div class="metric-hero">
      <div class="num">${fmt(m.total_units)}</div>
      <div class="lbl">housing units mapped</div>
    </div>
    <div class="metric-sub">${fmt(m.total_jobs)} estimated jobs &middot; ${fmt(m.projects_mapped)} projects</div>

    <div class="metric-pcts">
      <div class="pct">
        <div class="pct-num" style="color:#34c759">${m.pct_units_green}%</div>
        <div class="pct-lbl">units in green zones</div>
      </div>
      <div class="pct">
        <div class="pct-num" style="color:#3aa0ff">${m.pct_units_tpa}%</div>
        <div class="pct-lbl">units in transit priority areas</div>
      </div>
    </div>

    <div class="metric-section">Top jurisdictions by pipeline units</div>
    <div class="jlist">${top}</div>
  `;
}

map.on("load", async () => {
  setStatus("Loading projects&hellip;");

  let geojson;
  try {
    const res = await fetch("data/pipeline.geojson", { cache: "no-cache" });
    if (!res.ok) throw new Error(res.status);
    geojson = await res.json();
  } catch (e) {
    setStatus(
      "No geocoded projects yet.<br>Run <code>tools/geocode.py</code> then " +
      "<code>tools/export_geojson.py</code> to populate the map."
    );
    document.getElementById("legend-count").textContent = "0 projects";
    return;
  }

  const features = geojson.features || [];
  setStatus(features.length ? null : "No projects with coordinates yet.");

  map.addSource("projects", { type: "geojson", data: geojson });

  // ---- Project points: graduated circles, collapsing to small dots on zoom-in ----
  map.addLayer({
    id: "projects-circles",
    type: "circle",
    source: "projects",
    paint: {
      "circle-color": [
        "match", ["get", "color_bucket"],
        "residential", BUCKET_COLORS.residential,
        "mixed",       BUCKET_COLORS.mixed,
        "nonres",      BUCKET_COLORS.nonres,
        "#9aa0a6",
      ],
      // zoom-and-data driven: graduated by per-feature `radius` when zoomed out,
      // shrinking to a uniform small dot once labels take over (~zoom 14).
      "circle-radius": [
        "interpolate", ["linear"], ["zoom"],
        8,  ["get", "radius"],
        12, ["get", "radius"],
        14, 3.5,
        17, 4.5,
      ],
      "circle-opacity": [
        "match", ["get", "geocode_quality"],
        "exact", 0.92,
        "intersection", 0.88,
        "approximate", 0.55,
        "city_only", 0.4,
        0.85,
      ],
      "circle-stroke-width": 1,
      "circle-stroke-color": "rgba(255,255,255,0.6)",
      "circle-stroke-opacity": 0.55,
    },
  });

  // ---- Labels: project name + units/jobs, on zoom-in ----
  map.addLayer({
    id: "projects-labels",
    type: "symbol",
    source: "projects",
    minzoom: 13,
    layout: {
      "text-field": ["get", "label_text"],
      "text-font": ["Noto Sans Regular"],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10.5, 17, 13.5],
      "text-anchor": "top",
      "text-offset": [0, 0.7],
      "text-max-width": 9,
      "text-allow-overlap": false,
      "text-optional": true,
      "text-line-height": 1.15,
    },
    paint: {
      "text-color": "#ffffff",
      "text-halo-color": "#000000",
      "text-halo-width": 1.4,
      "text-halo-blur": 0.4,
    },
  });

  addBoundaries();
  renderMetrics(geojson.metrics);

  if (features.length) {
    const b = new maplibregl.LngLatBounds();
    let any = false;
    for (const f of features) {
      const c = f.geometry && f.geometry.coordinates;
      if (c && isFinite(c[0]) && isFinite(c[1])) { b.extend(c); any = true; }
    }
    if (any) map.fitBounds(b, { padding: 70, maxZoom: 12, duration: 0 });
  }

  document.getElementById("legend-count").textContent =
    `${features.length} project${features.length === 1 ? "" : "s"} mapped`;

  // ---- Interactions ----
  const hoverTip = new maplibregl.Popup({
    closeButton: false, closeOnClick: false, className: "hover-tip", offset: 12,
  });
  map.on("mouseenter", "projects-circles", (e) => {
    map.getCanvas().style.cursor = "pointer";
    const f = e.features[0];
    hoverTip.setLngLat(f.geometry.coordinates)
      .setText(f.properties.project_name || "(unnamed project)")
      .addTo(map);
  });
  map.on("mousemove", "projects-circles", (e) => {
    if (e.features[0]) hoverTip.setLngLat(e.features[0].geometry.coordinates);
  });
  map.on("mouseleave", "projects-circles", () => {
    map.getCanvas().style.cursor = "";
    hoverTip.remove();
  });
  map.on("click", "projects-circles", (e) => {
    if (e.features[0]) openDetail(e.features[0].properties);
  });
});

// ---- Detail dialog ----
const FIELD_LABELS = {
  project_number: "Project #",
  jurisdiction: "Jurisdiction",
  county: "County",
  project_type: "Type",
  address: "Address",
  units: "Housing units",
  affordable: "Affordable",
  hotel_rooms: "Hotel rooms",
  senior: "Senior housing",
  residential_care: "Residential care",
  nonres_sqft: "Non-res sq ft",
  jobs_estimated: "Estimated jobs",
  source_acres: "Site acres",
  res_den: "Density (du/ac)",
  parking_spaces: "Parking spaces",
  developer: "Developer",
  current_status: "Status",
  apn: "APN",
  entry_date: "Source date",
  notes: "Notes",
  geocode_quality: "Geocode precision",
};
const FIELD_ORDER = [
  "project_number", "jurisdiction", "county", "project_type", "address",
  "units", "affordable", "hotel_rooms", "senior", "residential_care",
  "nonres_sqft", "jobs_estimated", "source_acres", "res_den", "parking_spaces",
  "developer", "current_status", "apn", "entry_date", "notes", "geocode_quality",
];

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}
function hasVal(v) { return v !== null && v !== undefined && String(v).trim() !== ""; }

function openDetail(p) {
  const bucket = p.color_bucket;
  const chipColor = BUCKET_COLORS[bucket] || "#9aa0a6";
  const metricVal = p.label_metric_value;
  const metricLbl = p.label_metric_label;

  let html = "";
  html += `<span class="detail-chip" style="background:${chipColor}">${esc(BUCKET_LABELS[bucket] || p.project_type || "Project")}</span>`;
  html += `<div class="detail-name">${esc(p.project_name || "(unnamed project)")}</div>`;
  html += `<div class="detail-sub">${esc([p.jurisdiction, p.county && p.county + " County"].filter(hasVal).join(" · "))}</div>`;

  const flags = [];
  if (Number(p.in_green_zone)) flags.push(`<span class="flag flag-green">In green zone</span>`);
  if (Number(p.in_tpa)) flags.push(`<span class="flag flag-tpa">Transit priority area</span>`);
  if (flags.length) html += `<div class="detail-flags">${flags.join("")}</div>`;

  if (hasVal(metricVal) && Number(metricVal) > 0) {
    html += `<div class="detail-metric"><div><div class="num">${esc(metricVal)}</div><div class="lbl">${esc(metricLbl || "")}</div></div></div>`;
  }

  html += `<table class="detail-table">`;
  for (const key of FIELD_ORDER) {
    let v = p[key];
    if (!hasVal(v)) continue;
    v = key === "geocode_quality" ? `<span class="quality-badge">${esc(v)}</span>` : esc(v);
    html += `<tr><th>${esc(FIELD_LABELS[key] || key)}</th><td>${v}</td></tr>`;
  }
  if (hasVal(p.source)) {
    html += `<tr><th>Source</th><td><a href="${esc(p.source)}" target="_blank" rel="noopener">View agenda / article ↗</a></td></tr>`;
  }
  html += `</table>`;

  document.getElementById("detail-body").innerHTML = html;
  const panel = document.getElementById("detail");
  panel.classList.add("open");
  panel.setAttribute("aria-hidden", "false");
}

document.getElementById("detail-close").addEventListener("click", () => {
  const panel = document.getElementById("detail");
  panel.classList.remove("open");
  panel.setAttribute("aria-hidden", "true");
});

// ---- Overlay layers (loaded on demand; semi-transparent; beneath the points) ----
const OVERLAYS = {
  greenzones: {
    file: "data/overlays/green_zones.geojson",
    add(data) {
      map.addSource("ov-greenzones", { type: "geojson", data });
      map.addLayer({
        id: "ov-greenzones-fill", type: "fill", source: "ov-greenzones",
        paint: { "fill-color": "#34c759", "fill-opacity": 0.22 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-greenzones-line", type: "line", source: "ov-greenzones",
        paint: { "line-color": "#34c759", "line-opacity": 0.6, "line-width": 0.8 },
      }, "projects-circles");
    },
  },
  transit: {
    file: "data/overlays/transit_buffers.geojson",
    add(data) {
      map.addSource("ov-transit", { type: "geojson", data });
      map.addLayer({
        id: "ov-transit-fill", type: "fill", source: "ov-transit",
        paint: { "fill-color": "#3aa0ff", "fill-opacity": 0.18 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-transit-line", type: "line", source: "ov-transit",
        paint: { "line-color": "#3aa0ff", "line-opacity": 0.5, "line-width": 0.6 },
      }, "projects-circles");
    },
  },
  comtypes: {
    file: "data/overlays/community_types.geojson",
    add(data) {
      map.addSource("ov-comtypes", { type: "geojson", data });
      const fillColor = [
        "match", ["get", "Webmap_ComType"],
        "Centers and Corridors", "#ff3b30",
        "Established Communities", "#9aa0a6",
        "Developing Communities", "#b14bff",
        "rgba(255,255,255,0.05)", // other comtypes: faint neutral
      ];
      map.addLayer({
        id: "ov-comtypes-fill", type: "fill", source: "ov-comtypes",
        paint: { "fill-color": fillColor, "fill-opacity": 0.22 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-comtypes-line", type: "line", source: "ov-comtypes",
        paint: { "line-color": fillColor, "line-opacity": 0.45, "line-width": 0.5 },
      }, "projects-circles");
    },
  },
};
const overlayLoaded = {};

async function toggleOverlay(key, checkbox) {
  const conf = OVERLAYS[key];
  const ids = Object.keys(map.style._layers).filter((id) => id.startsWith("ov-" + key));
  if (!checkbox.checked) {
    ids.forEach((id) => map.getLayer(id) && map.setLayoutProperty(id, "visibility", "none"));
    return;
  }
  if (overlayLoaded[key]) {
    ids.forEach((id) => map.getLayer(id) && map.setLayoutProperty(id, "visibility", "visible"));
    return;
  }
  try {
    const res = await fetch(conf.file, { cache: "no-cache" });
    if (!res.ok) throw new Error(res.status);
    conf.add(await res.json());
    overlayLoaded[key] = true;
  } catch (e) {
    checkbox.checked = false;
    document.getElementById("overlay-note").textContent = "That overlay isn't available yet.";
  }
}

document.getElementById("toggle-greenzones")
  .addEventListener("change", (e) => toggleOverlay("greenzones", e.target));
document.getElementById("toggle-transit")
  .addEventListener("change", (e) => toggleOverlay("transit", e.target));
document.getElementById("toggle-comtypes").addEventListener("change", (e) => {
  document.getElementById("comtype-legend").hidden = !e.target.checked;
  toggleOverlay("comtypes", e.target);
});
