/* SACOG Region Pipeline Project Inventory — map app
 * Pure front-end. Consumes data/pipeline.geojson (generated by tools/export_geojson.py)
 * plus the overlays in data/overlays/ (generated by tools/build_overlays.py).
 * No API key required: dark basemap = CARTO raster tiles, glyphs = protomaps fonts.
 */

// ---- Color scheme (must match tools/export_geojson.py EXPLICIT_BUCKET) ----
const BUCKET_COLORS = {
  residential: "#ffd400", // housing only
  mixed:       "#b14bff", // housing + jobs
  nonres:      "#ff3b30", // jobs only
};
const BUCKET_LABELS = {
  residential: "Residential",
  mixed:       "Mixed Use (Housing + Jobs)",
  nonres:      "Non-Residential",
};

// Historical housing-permit overlay: net-new units sized by circle, year-finaled
// by colour. A dark→light indigo→cyan gradient (chosen to be distinct from the
// pipeline yellow/purple/red), so older permits read deep and newer ones pale.
const PERMIT_COLORS = {
  early: "#1a237e", // 2001–2008 (deep indigo)
  mid:   "#2f80ed", // 2009–2019 (mid blue)
  late:  "#7dd3fc", // 2020–2025 (light sky)
};
const PERMIT_BUCKETS = ["early", "mid", "late"];

const DEFAULT_VIEW = { center: [-121.3, 38.72], zoom: 8.2 }; // SACOG region fallback

// The parcel transition: zoomed out, every project is a graduated dot; zoomed in
// (~zoom 13, where labels appear) projects that have a real parcel footprint show
// it instead. `dotFade` fades a dot to nothing across 12.5→13.5 *iff* the project
// has a parcel; projects without one (has_parcel=0) keep their dot at all zooms.
// A "zoom" expression must be the top-level input to interpolate/step, so the fade
// is built as a camera+data composite: zoom drives the interpolate, and the
// per-feature base opacity (zoom-independent) is supplied as the stop outputs.
const PARCEL_ZOOM = 13;
function dotFade(base) {
  return [
    "interpolate", ["linear"], ["zoom"],
    PARCEL_ZOOM - 0.5, base,
    PARCEL_ZOOM + 0.5, ["case", ["==", ["get", "has_parcel"], 1], 0, base],
  ];
}

// ---- Basemap style: black background + dark raster tiles, no token ----
const style = {
  version: 8,
  glyphs: "https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf",
  sources: {
    "carto-dark": {
      type: "raster",
      tiles: [
        "https://a.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://b.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://c.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
        "https://d.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png",
      ],
      tileSize: 256,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
    },
    "esri-imagery": {
      type: "raster",
      tiles: [
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
      ],
      tileSize: 256,
      maxzoom: 19,
      attribution: 'Imagery &copy; <a href="https://www.esri.com/">Esri</a>, Maxar, Earthstar Geographics, and the GIS User Community',
    },
    // Labels-only raster (street + place names) so zoomed-in views have context
    // the no-labels basemap omits. Faded in by zoom and kept beneath the data.
    "carto-dark-labels": {
      type: "raster",
      tiles: [
        "https://a.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}.png",
        "https://b.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}.png",
        "https://c.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}.png",
        "https://d.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}.png",
      ],
      tileSize: 256,
    },
  },
  layers: [
    { id: "bg", type: "background", paint: { "background-color": "#000000" } },
    { id: "carto-dark", type: "raster", source: "carto-dark", paint: { "raster-opacity": 0.82 } },
    { id: "esri-imagery", type: "raster", source: "esri-imagery", layout: { visibility: "none" } },
    // Street/place labels appear as you zoom in (off at the regional view to keep
    // it clean); shown only on the dark base (hidden over imagery in setBasemap).
    { id: "carto-dark-labels", type: "raster", source: "carto-dark-labels",
      paint: { "raster-opacity": ["interpolate", ["linear"], ["zoom"], 12.5, 0, 14, 0.85] } },
  ],
};

// Parcel polygons read fine on the dark base at low opacity, but over the busy
// aerial photo they need a stronger fill and heavier outline to stay legible.
// styleParcelsForBasemap() swaps the paint props whenever the base changes.
let currentBasemap = "dark";
const PARCEL_FILL = {
  dark:    ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM - 0.5, 0, PARCEL_ZOOM + 0.5, 0.34, 16, 0.42],
  imagery: ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM - 0.5, 0, PARCEL_ZOOM + 0.5, 0.5,  16, 0.62],
};
const PARCEL_LINE_W = {
  dark:    ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM, 1,   17, 2.2],
  imagery: ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM, 1.6, 17, 3.4],
};
function styleParcelsForBasemap() {
  if (map.getLayer("parcels-fill"))
    map.setPaintProperty("parcels-fill", "fill-opacity", PARCEL_FILL[currentBasemap]);
  if (map.getLayer("parcels-line"))
    map.setPaintProperty("parcels-line", "line-width", PARCEL_LINE_W[currentBasemap]);
}

// Switch base imagery without rebuilding overlays/points (both rasters preloaded).
function setBasemap(which) {
  const dark = which !== "imagery";
  currentBasemap = dark ? "dark" : "imagery";
  if (map.getLayer("carto-dark"))
    map.setLayoutProperty("carto-dark", "visibility", dark ? "visible" : "none");
  if (map.getLayer("esri-imagery"))
    map.setLayoutProperty("esri-imagery", "visibility", dark ? "none" : "visible");
  // Street/place labels only belong over the dark base — they're illegible on imagery.
  if (map.getLayer("carto-dark-labels"))
    map.setLayoutProperty("carto-dark-labels", "visibility", dark ? "visible" : "none");
  document.body.classList.toggle("imagery-base", !dark);
  styleParcelsForBasemap();
}

const map = new maplibregl.Map({
  container: "map",
  style,
  center: DEFAULT_VIEW.center,
  zoom: DEFAULT_VIEW.zoom,
  attributionControl: { compact: true },
});
map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");

function setStatus(msg) {
  let el = document.getElementById("status-msg");
  if (!msg) { if (el) el.remove(); return; }
  if (!el) {
    el = document.createElement("div");
    el.id = "status-msg";
    document.body.appendChild(el);
  }
  el.innerHTML = msg;
}

function titleCase(s) {
  return String(s || "").toLowerCase().replace(/\b([a-z])/g, (_, c) => c.toUpperCase());
}

// ---- City + county boundaries (shown automatically) ----
// CITY_NAME is present (as null) on county features, so test the *value* with
// to-boolean rather than `has`, which would be true even for the null key.
const IS_CITY = ["to-boolean", ["get", "CITY_NAME"]];
const IS_COUNTY = ["!", ["to-boolean", ["get", "CITY_NAME"]]];

function addBoundaries() {
  const url = "data/overlays/city_county_boundary.geojson";
  fetch(url, { cache: "no-cache" })
    .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
    .then((data) => {
      // Bake a Title-Case display name (source values are ALL CAPS).
      for (const f of data.features || []) {
        const p = f.properties || {};
        p.NAME_TC = titleCase(p.CITY_NAME || p.COUNTY || "");
      }
      map.addSource("boundary", { type: "geojson", data });
      // County outlines — brighter.
      map.addLayer({
        id: "boundary-county",
        type: "line",
        source: "boundary",
        filter: IS_COUNTY,
        paint: { "line-color": "#ffffff", "line-opacity": 0.34, "line-width": 1.3 },
      }, "projects-circles");
      // City outlines — dimmer, dashed.
      map.addLayer({
        id: "boundary-city",
        type: "line",
        source: "boundary",
        filter: IS_CITY,
        paint: {
          "line-color": "#9fb4d0",
          "line-opacity": 0.32,
          "line-width": 0.8,
          "line-dasharray": [2, 2],
        },
      }, "projects-circles");
      // Faint county name labels for orientation (low zoom only).
      map.addLayer({
        id: "boundary-county-label",
        type: "symbol",
        source: "boundary",
        filter: IS_COUNTY,
        maxzoom: 10,
        layout: {
          "text-field": ["get", "NAME_TC"],
          "text-font": ["Noto Sans Regular"],
          "text-size": 11,
          "text-letter-spacing": 0.12,
          "symbol-placement": "point",
        },
        paint: {
          "text-color": "#7f8794",
          "text-halo-color": "#000000",
          "text-halo-width": 1.2,
        },
      }, "projects-circles");
      // Subtle city name labels (mid zoom; collision-managed so they stay quiet).
      map.addLayer({
        id: "boundary-city-label",
        type: "symbol",
        source: "boundary",
        filter: IS_CITY,
        minzoom: 8.5,
        layout: {
          "text-field": ["get", "NAME_TC"],
          "text-font": ["Noto Sans Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 8.5, 10, 13, 13],
          "text-letter-spacing": 0.04,
          "symbol-placement": "point",
          "text-max-width": 8,
          "text-allow-overlap": false,
          "text-optional": true,
        },
        paint: {
          "text-color": "#c4cedd",
          "text-opacity": 0.72,
          "text-halo-color": "#000000",
          "text-halo-width": 1.1,
        },
      }, "projects-circles");
    })
    .catch(() => { /* boundaries optional; ignore if absent */ });
}

// ---- Metrics panel ----
function fmt(n) { return Number(n).toLocaleString("en-US"); }

// The exporter classifies each project geographically (city polygon, else
// "Unincorporated <County> County") and emits the final display name, so the
// ranking shows it verbatim — no "(city)"/"(county)" suffixes.
function jurisLabel(j) {
  return j.name || "";
}

function renderMetrics(m) {
  if (!m) return;
  const top = (m.top_jurisdictions || [])
    .map((j) => {
      const pct = m.top_jurisdictions[0].units
        ? Math.round((j.units / m.top_jurisdictions[0].units) * 100)
        : 0;
      return `<div class="jrow">
          <div class="jbar" style="width:${pct}%"></div>
          <span class="jname">${esc(jurisLabel(j))}</span>
          <span class="jval">${fmt(j.units)}</span>
        </div>`;
    })
    .join("");

  document.getElementById("metrics-body").innerHTML = `
    <div class="metric-hero">
      <div class="num">${fmt(m.total_units)}</div>
      <div class="lbl">Housing Units Mapped</div>
    </div>
    <div class="metric-hero">
      <div class="num">${fmt(m.total_jobs)}</div>
      <div class="lbl">Estimated Jobs</div>
    </div>
    <div class="metric-hero">
      <div class="num">${fmt(m.projects_mapped)}</div>
      <div class="lbl">Projects Mapped</div>
    </div>

    <div class="metric-pcts">
      <div class="pct">
        <div class="pct-num" style="color:#34c759">${m.pct_units_green}%</div>
        <div class="pct-lbl">Units in Green Zones</div>
      </div>
      <div class="pct">
        <div class="pct-num" style="color:#3aa0ff">${m.pct_units_tpa}%</div>
        <div class="pct-lbl">Units in Transit Priority Areas</div>
      </div>
    </div>

    <div class="metric-section">Housing Pipeline Rankings</div>
    <div class="jlist">${top}</div>
  `;
}

map.on("load", async () => {
  setStatus("Loading projects&hellip;");

  let geojson;
  try {
    const res = await fetch("data/pipeline.geojson", { cache: "no-cache" });
    if (!res.ok) throw new Error(res.status);
    geojson = await res.json();
  } catch (e) {
    setStatus(
      "No geocoded projects yet.<br>Run <code>tools/geocode.py</code> then " +
      "<code>tools/export_geojson.py</code> to populate the map."
    );
    return;
  }

  const features = geojson.features || [];
  setStatus(features.length ? null : "No projects with coordinates yet.");

  map.addSource("projects", { type: "geojson", data: geojson });

  // ---- Project points: graduated circles, collapsing to small dots on zoom-in ----
  map.addLayer({
    id: "projects-circles",
    type: "circle",
    source: "projects",
    // Draw the smallest dots last (on top) so a big circle never buries a small
    // neighbour. circle-sort-key sorts ascending, so negate radius: big → very
    // negative (drawn first/under), small → near zero (drawn last/over).
    layout: { "circle-sort-key": ["*", -1, ["get", "radius"]] },
    paint: {
      "circle-color": [
        "match", ["get", "color_bucket"],
        "residential", BUCKET_COLORS.residential,
        "mixed",       BUCKET_COLORS.mixed,
        "nonres",      BUCKET_COLORS.nonres,
        "#9aa0a6",
      ],
      // zoom-and-data driven: graduated by per-feature `radius` when zoomed out,
      // shrinking to a uniform small dot once labels take over (~zoom 14).
      "circle-radius": [
        "interpolate", ["linear"], ["zoom"],
        8,  ["get", "radius"],
        12, ["get", "radius"],
        14, 3.5,
        17, 4.5,
      ],
      "circle-opacity": dotFade(
        ["match", ["get", "geocode_quality"],
          "exact", 0.92,
          "intersection", 0.88,
          "approximate", 0.55,
          "city_only", 0.4,
          0.85,
        ]
      ),
      "circle-stroke-width": 1,
      "circle-stroke-color": "rgba(255,255,255,0.6)",
      "circle-stroke-opacity": dotFade(0.55),
    },
  });

  // ---- Labels: project name + units/jobs, on zoom-in ----
  map.addLayer({
    id: "projects-labels",
    type: "symbol",
    source: "projects",
    minzoom: 13,
    layout: {
      "text-field": ["get", "label_text"],
      "text-font": ["Noto Sans Regular"],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10.5, 17, 13.5],
      "text-anchor": "top",
      "text-offset": [0, 0.7],
      "text-max-width": 9,
      "text-allow-overlap": false,
      "text-optional": true,
      "text-line-height": 1.15,
    },
    paint: {
      "text-color": "#ffffff",
      "text-halo-color": "#000000",
      "text-halo-width": 1.4,
      "text-halo-blur": 0.4,
    },
  });

  addBoundaries();
  renderMetrics(geojson.metrics);

  if (features.length) {
    const b = new maplibregl.LngLatBounds();
    let any = false;
    for (const f of features) {
      const c = f.geometry && f.geometry.coordinates;
      if (c && isFinite(c[0]) && isFinite(c[1])) { b.extend(c); any = true; }
    }
    if (any) map.fitBounds(b, { padding: 70, maxZoom: 12, duration: 0 });
  }

  // ---- Interactions ----
  const hoverTip = new maplibregl.Popup({
    closeButton: false, closeOnClick: false, className: "hover-tip", offset: 12,
  });
  map.on("mouseenter", "projects-circles", (e) => {
    map.getCanvas().style.cursor = "pointer";
    const f = e.features[0];
    hoverTip.setLngLat(f.geometry.coordinates)
      .setText(f.properties.project_name || "(unnamed project)")
      .addTo(map);
  });
  map.on("mousemove", "projects-circles", (e) => {
    if (e.features[0]) hoverTip.setLngLat(e.features[0].geometry.coordinates);
  });
  map.on("mouseleave", "projects-circles", () => {
    map.getCanvas().style.cursor = "";
    hoverTip.remove();
  });
  map.on("click", "projects-circles", (e) => {
    if (Editor.editing) return;          // editing routes clicks to parcel-picking
    const f = e.features[0];
    if (f) openDetail(f.properties, pointOf(f, e.lngLat));
  });

  // Single click router for the local parcel editor (dormant unless the edit
  // backend is present + a project is open in edit mode). Layer click handlers
  // above bail out while Editor.editing, so every edit-mode click funnels here.
  map.on("click", (e) => Editor.onMapClick(e));

  // ---- Project parcels: real footprints at label zoom (dots take over zoomed out) ----
  try {
    const pres = await fetch("data/pipeline_parcels.geojson", { cache: "no-cache" });
    if (pres.ok) {
      map.addSource("parcels", { type: "geojson", data: await pres.json() });
      const parcelColor = [
        "match", ["get", "color_bucket"],
        "residential", BUCKET_COLORS.residential,
        "mixed",       BUCKET_COLORS.mixed,
        "nonres",      BUCKET_COLORS.nonres,
        "#9aa0a6",
      ];
      // Inserted beneath the labels (so names stay on top) but above the dots, so
      // the footprint reads as the dot's replacement once it fades in.
      map.addLayer({
        id: "parcels-fill", type: "fill", source: "parcels", minzoom: PARCEL_ZOOM - 0.5,
        paint: {
          "fill-color": parcelColor,
          "fill-opacity": ["interpolate", ["linear"], ["zoom"],
            PARCEL_ZOOM - 0.5, 0, PARCEL_ZOOM + 0.5, 0.34, 16, 0.42],
        },
      }, "projects-labels");
      map.addLayer({
        id: "parcels-line", type: "line", source: "parcels", minzoom: PARCEL_ZOOM - 0.5,
        paint: {
          "line-color": parcelColor,
          "line-opacity": ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM - 0.5, 0, PARCEL_ZOOM + 0.5, 0.95],
          "line-width": ["interpolate", ["linear"], ["zoom"], PARCEL_ZOOM, 1, 17, 2.2],
        },
      }, "projects-labels");
      // Parcels load after the basemap/pipeline toggles may already have changed,
      // so reconcile both now that the layers exist.
      styleParcelsForBasemap();
      applyPipelineVisibility();
      // these parcels were just inserted above the permit dots; if the permit
      // overlay is on, lift the dots back above the parcels.
      if (overlayLoaded.permits) raisePermitsAboveParcels();

      // Parcel hover + click reuse the same tooltip and detail dialog as the dots.
      map.on("mouseenter", "parcels-fill", (e) => {
        map.getCanvas().style.cursor = "pointer";
        hoverTip.setLngLat(e.lngLat)
          .setText(e.features[0].properties.project_name || "(unnamed project)")
          .addTo(map);
      });
      map.on("mousemove", "parcels-fill", (e) => hoverTip.setLngLat(e.lngLat));
      map.on("mouseleave", "parcels-fill", () => {
        map.getCanvas().style.cursor = "";
        hoverTip.remove();
      });
      map.on("click", "parcels-fill", (e) => {
        if (Editor.editing) return;       // editing routes clicks to parcel-picking
        if (e.features[0]) openDetail(e.features[0].properties, e.lngLat);
      });
    }
  } catch (e) { /* parcels optional; dots still work without them */ }
});

// ---- Detail dialog ----
const FIELD_LABELS = {
  project_number: "Project #",
  jurisdiction: "Jurisdiction",
  county: "County",
  project_type: "Type",
  address: "Address",
  units: "Housing Units",
  remaining_units: "Remaining Units",
  affordable: "Affordable",
  hotel_rooms: "Hotel Rooms",
  senior: "Senior Housing",
  residential_care: "Residential Care",
  nonres_sqft: "Non-Res Sq Ft",
  jobs_estimated: "Estimated Jobs",
  source_acres: "Site Acres",
  res_den: "Density (du/ac)",
  parking_spaces: "Parking Spaces",
  developer: "Developer",
  current_status: "Status",
  apn: "APN",
  entry_date: "Source Date",
  notes: "Notes",
  geocode_quality: "Geocode Precision",
};
const FIELD_ORDER = [
  "project_number", "jurisdiction", "county", "project_type", "address",
  "units", "remaining_units", "affordable", "hotel_rooms", "senior", "residential_care",
  "nonres_sqft", "jobs_estimated", "source_acres", "res_den", "parking_spaces",
  "developer", "current_status", "apn", "entry_date", "notes", "geocode_quality",
];

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}
function hasVal(v) { return v !== null && v !== undefined && String(v).trim() !== ""; }

// Best click point for a feature: a Point's own coordinates (exact project point)
// else the raw click location. Used to seed the parcel editor's window load.
function pointOf(f, lngLat) {
  const g = f && f.geometry;
  if (g && g.type === "Point" && g.coordinates)
    return { lng: g.coordinates[0], lat: g.coordinates[1] };
  return lngLat || null;
}

// The project currently shown in the sidebar — its properties + the point we
// opened it from. The parcel editor reads this when "Edit parcels" is clicked.
let detailCtx = null;

function closeDetail() {
  const wasEditing = Editor.editing;
  if (wasEditing) Editor.endEdit();
  const panel = document.getElementById("detail");
  panel.classList.remove("open");
  panel.setAttribute("aria-hidden", "true");
  detailCtx = null;
  if (wasEditing) setStatus(null);   // clear the lingering edit status message
}

// Build the "Source" cell from the classified provenance.
function sourceRow(p) {
  const type = p.source_type;
  const label = p.source_label;
  const url = p.source_url;
  if (!hasVal(label) && !hasVal(url)) return "";
  if (hasVal(url)) {
    const linkText = type === "agenda" ? "View staff report / agenda" : (label || "Open source");
    return `<a href="${esc(url)}" target="_blank" rel="noopener">${esc(linkText)} ↗</a>`;
  }
  return esc(label || "—");
}

function openDetail(p, lngLat) {
  detailCtx = { p, lngLat: lngLat || null };
  const bucket = p.color_bucket;
  const chipColor = BUCKET_COLORS[bucket] || "#9aa0a6";
  const metricVal = p.label_metric_value;
  const metricLbl = p.label_metric_label;

  let html = "";
  html += `<span class="detail-chip" style="background:${chipColor}">${esc(BUCKET_LABELS[bucket] || p.project_type || "Project")}</span>`;
  html += `<div class="detail-name">${esc(p.project_name || "(unnamed project)")}</div>`;
  html += `<div class="detail-sub">${esc([p.jurisdiction, p.county && p.county + " County"].filter(hasVal).join(" · "))}</div>`;

  const flags = [];
  if (Number(p.in_green_zone)) flags.push(`<span class="flag flag-green">In Green Zone</span>`);
  if (Number(p.in_tpa)) flags.push(`<span class="flag flag-tpa">Transit Priority Area</span>`);
  if (flags.length) html += `<div class="detail-flags">${flags.join("")}</div>`;

  if (hasVal(metricVal) && Number(metricVal) > 0) {
    html += `<div class="detail-metric"><div><div class="num">${esc(metricVal)}</div><div class="lbl">${esc(metricLbl || "")}</div></div></div>`;
  }

  html += `<table class="detail-table">`;
  for (const key of FIELD_ORDER) {
    let v = p[key];
    if (!hasVal(v)) continue;
    v = key === "geocode_quality" ? `<span class="quality-badge">${esc(v)}</span>` : esc(v);
    html += `<tr><th>${esc(FIELD_LABELS[key] || key)}</th><td>${v}</td></tr>`;
  }
  const srcRow = sourceRow(p);
  if (srcRow) html += `<tr><th>Source</th><td>${srcRow}</td></tr>`;
  html += `</table>`;

  // Local-only editor controls at the bottom of the sidebar (dormant on the
  // public build, where Editor.available stays false).
  if (Editor.available) html += Editor.footerHTML();

  document.getElementById("detail-body").innerHTML = html;
  const panel = document.getElementById("detail");
  panel.classList.add("open");
  panel.setAttribute("aria-hidden", "false");
}

document.getElementById("detail-close").addEventListener("click", closeDetail);

// One delegated handler for every editor button rendered inside the sidebar
// (the footer's Edit/Delete and the edit panel's Save/Reload/Remove/Cancel).
document.getElementById("detail").addEventListener("click", (e) => {
  const b = e.target.closest("[data-ed-act]");
  if (!b) return;
  const fn = {
    edit: Editor.beginEdit, delete: Editor.deleteProject,
    save: Editor.save, reload: Editor.reloadHere,
    clearfoot: Editor.clear, cancel: Editor.cancel,
  }[b.dataset.edAct];
  if (fn) fn.call(Editor);
});

// ---- Overlay layers (loaded on demand; semi-transparent; beneath the points) ----
const OVERLAYS = {
  greenzones: {
    file: "data/overlays/green_zones.geojson",
    add(data) {
      map.addSource("ov-greenzones", { type: "geojson", data });
      map.addLayer({
        id: "ov-greenzones-fill", type: "fill", source: "ov-greenzones",
        paint: { "fill-color": "#34c759", "fill-opacity": 0.22 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-greenzones-line", type: "line", source: "ov-greenzones",
        paint: { "line-color": "#34c759", "line-opacity": 0.6, "line-width": 0.8 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-greenzones-label", type: "symbol", source: "ov-greenzones", minzoom: 10.5,
        filter: ["==", ["geometry-type"], "Point"],
        layout: {
          "text-field": ["get", "label"],
          "text-font": ["Noto Sans Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 10.5, 10, 14, 12.5],
          "text-max-width": 8, "symbol-placement": "point",
          "text-allow-overlap": false, "text-optional": true,
        },
        paint: {
          "text-color": "#86e6a6", "text-halo-color": "#04210f", "text-halo-width": 1.3,
        },
      });
    },
  },
  transit: {
    file: "data/overlays/transit_buffers.geojson",
    add(data) {
      map.addSource("ov-transit", { type: "geojson", data });
      map.addLayer({
        id: "ov-transit-fill", type: "fill", source: "ov-transit",
        paint: { "fill-color": "#3aa0ff", "fill-opacity": 0.18 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-transit-line", type: "line", source: "ov-transit",
        paint: { "line-color": "#3aa0ff", "line-opacity": 0.5, "line-width": 0.6 },
      }, "projects-circles");
    },
  },
  comtypes: {
    file: "data/overlays/community_types.geojson",
    add(data) {
      map.addSource("ov-comtypes", { type: "geojson", data });
      const fillColor = [
        "match", ["get", "Webmap_ComType"],
        "Centers and Corridors", "#ff3b30",
        "Established Communities", "#9aa0a6",
        "Developing Communities", "#b14bff",
        "Rural Residential", "#ffe98a",
        "rgba(255,255,255,0.05)", // other comtypes: faint neutral
      ];
      map.addLayer({
        id: "ov-comtypes-fill", type: "fill", source: "ov-comtypes",
        paint: { "fill-color": fillColor, "fill-opacity": 0.22 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-comtypes-line", type: "line", source: "ov-comtypes",
        paint: { "line-color": fillColor, "line-opacity": 0.45, "line-width": 0.5 },
      }, "projects-circles");
      map.addLayer({
        id: "ov-comtypes-label", type: "symbol", source: "ov-comtypes", minzoom: 11,
        filter: ["==", ["geometry-type"], "Point"],
        layout: {
          "text-field": ["get", "label"],
          "text-font": ["Noto Sans Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 11, 9.5, 14, 12],
          "text-max-width": 9, "symbol-placement": "point",
          "text-allow-overlap": false, "text-optional": true,
        },
        paint: {
          "text-color": "#e7daf6", "text-halo-color": "#1a0a2e", "text-halo-width": 1.3,
        },
      });
    },
  },
  permits: {
    file: "data/overlays/housing_permits.geojson",
    add(data) {
      map.addSource("ov-permits", { type: "geojson", data });
      // radius ∝ √units (so area ∝ units); grows a little when zoomed in.
      const u = ["sqrt", ["max", 1, ["coalesce", ["get", "u"], 1]]];
      const radius = [
        "interpolate", ["linear"], ["zoom"],
        9,  ["interpolate", ["linear"], u, 1, 1.6, 6, 4, 18.8, 9],
        14, ["interpolate", ["linear"], u, 1, 3.2, 6, 8, 18.8, 18],
      ];
      // Each time period is its own layer (id ov-permits-<bucket>) so it can be
      // toggled independently; the year filter splits the single source.
      const yr = ["coalesce", ["get", "y"], 2005];
      const buckets = [
        ["early", PERMIT_COLORS.early, ["<=", yr, 2008]],
        ["mid",   PERMIT_COLORS.mid,   ["all", [">=", yr, 2009], ["<=", yr, 2019]]],
        ["late",  PERMIT_COLORS.late,  [">=", yr, 2020]],
      ];
      const ids = [];
      for (const [name, color, filter] of buckets) {
        const id = "ov-permits-" + name;
        ids.push(id);
        map.addLayer({
          id, type: "circle", source: "ov-permits", filter,
          paint: {
            "circle-color": color,
            "circle-radius": radius,
            "circle-opacity": 0.7,
            "circle-stroke-color": "rgba(0,0,0,0.55)",
            "circle-stroke-width": ["interpolate", ["linear"], ["zoom"], 11, 0, 15, 0.5],
          },
        }, "projects-circles");
      }

      // lightweight hover readout (units · year) on any bucket layer
      const tip = new maplibregl.Popup({
        closeButton: false, closeOnClick: false, className: "hover-tip", offset: 10,
      });
      for (const id of ids) {
        map.on("mouseenter", id, (e) => {
          map.getCanvas().style.cursor = "crosshair";
          const p = e.features[0].properties;
          const y = p.y ? ` · finaled ${p.y}` : "";
          tip.setLngLat(e.features[0].geometry.coordinates)
            .setText(`${p.u} net-new unit${p.u == 1 ? "" : "s"}${y}`)
            .addTo(map);
        });
        map.on("mousemove", id, (e) => {
          if (e.features[0]) tip.setLngLat(e.features[0].geometry.coordinates);
        });
        map.on("mouseleave", id, () => {
          map.getCanvas().style.cursor = "";
          tip.remove();
        });
      }
    },
  },
};
const overlayLoaded = {};

async function toggleOverlay(key, checkbox) {
  const conf = OVERLAYS[key];
  const ids = Object.keys(map.style._layers).filter((id) => id.startsWith("ov-" + key));
  if (!checkbox.checked) {
    ids.forEach((id) => map.getLayer(id) && map.setLayoutProperty(id, "visibility", "none"));
    return;
  }
  if (overlayLoaded[key]) {
    ids.forEach((id) => map.getLayer(id) && map.setLayoutProperty(id, "visibility", "visible"));
    return;
  }
  try {
    const res = await fetch(conf.file, { cache: "no-cache" });
    if (!res.ok) throw new Error(res.status);
    conf.add(await res.json());
    overlayLoaded[key] = true;
  } catch (e) {
    checkbox.checked = false;
    document.getElementById("overlay-note").textContent = "That overlay isn't available yet.";
  }
}

document.getElementById("toggle-greenzones")
  .addEventListener("change", (e) => toggleOverlay("greenzones", e.target));
document.getElementById("toggle-transit")
  .addEventListener("change", (e) => toggleOverlay("transit", e.target));
document.getElementById("toggle-comtypes").addEventListener("change", (e) => {
  document.getElementById("comtype-legend").hidden = !e.target.checked;
  toggleOverlay("comtypes", e.target);
});
// Permit dots load beneath projects-circles (so they don't obscure the pipeline
// dots when zoomed out), but the pipeline PARCEL polygons sit above the dots and
// would otherwise cover the permits. Lift the permit layers to just beneath the
// name labels so they read on top of the parcels when the overlay is on.
function raisePermitsAboveParcels() {
  const before = map.getLayer("projects-labels") ? "projects-labels" : undefined;
  for (const b of PERMIT_BUCKETS) {        // early -> mid -> late, so late ends up on top
    const id = "ov-permits-" + b;
    if (map.getLayer(id)) map.moveLayer(id, before);
  }
}

// Show each permit bucket only when the master toggle AND its own sub-toggle are
// on. toggleOverlay() flips all three ov-permits-* layers together; this then
// narrows that down to the buckets the user actually wants visible.
function applyPermitSubVisibility() {
  const master = document.getElementById("toggle-permits").checked;
  for (const b of PERMIT_BUCKETS) {
    const id = "ov-permits-" + b;
    if (!map.getLayer(id)) continue;
    const sub = document.getElementById("pp-" + b);
    const vis = master && (!sub || sub.checked) ? "visible" : "none";
    map.setLayoutProperty(id, "visibility", vis);
  }
  if (master) raisePermitsAboveParcels();
}

// "Turn pipeline off" — temporarily hide the entire pipeline inventory (dots,
// labels, parcels) so the permits/overlays can be read on their own. Lives inside
// the permit legend, so it's only reachable while the permits panel is expanded.
const PIPELINE_LAYERS = ["parcels-fill", "parcels-line", "projects-labels", "projects-circles"];
function applyPipelineVisibility() {
  const off = document.getElementById("toggle-pipeline-off").checked;
  for (const id of PIPELINE_LAYERS) {
    if (map.getLayer(id)) map.setLayoutProperty(id, "visibility", off ? "none" : "visible");
  }
}
document.getElementById("toggle-pipeline-off")
  .addEventListener("change", applyPipelineVisibility);

document.getElementById("toggle-permits").addEventListener("change", (e) => {
  document.getElementById("permit-legend").hidden = !e.target.checked;
  // Collapsing the permits panel must never strand the pipeline in a hidden state.
  if (!e.target.checked) {
    const off = document.getElementById("toggle-pipeline-off");
    if (off && off.checked) { off.checked = false; applyPipelineVisibility(); }
  }
  document.getElementById("overlay-note").textContent =
    e.target.checked && !overlayLoaded.permits ? "Loading 193k permits…" : "";
  toggleOverlay("permits", e.target).then(() => {
    if (overlayLoaded.permits) document.getElementById("overlay-note").textContent = "";
    applyPermitSubVisibility();
  });
});
for (const b of PERMIT_BUCKETS) {
  const el = document.getElementById("pp-" + b);
  if (el) el.addEventListener("change", applyPermitSubVisibility);
}

// ---- Basemap switch (dark labels-off ↔ aerial imagery) ----
const bmButtons = { dark: document.getElementById("bm-dark"), imagery: document.getElementById("bm-imagery") };
function selectBasemap(which) {
  setBasemap(which);
  for (const [k, btn] of Object.entries(bmButtons)) {
    if (btn) btn.classList.toggle("active", k === which);
  }
}
if (bmButtons.dark) bmButtons.dark.addEventListener("click", () => selectBasemap("dark"));
if (bmButtons.imagery) bmButtons.imagery.addEventListener("click", () => selectBasemap("imagery"));

// ---- Pipeline Inputs dashboard (sources of the inventory) ----
let inputsData = null;

function inputItem(it) {
  const date = it.date ? `<span class="src-date">${esc(it.date)}</span>` : `<span class="src-date"></span>`;
  const name = it.url
    ? `<a href="${esc(it.url)}" target="_blank" rel="noopener">${esc(it.name)} ↗</a>`
    : esc(it.name);
  return `<li class="src-item">${date}<span class="src-name">${name}</span></li>`;
}

function feedItem(f) {
  return `<li class="src-feed"><a href="${esc(f.url)}" target="_blank" rel="noopener">${esc(f.name)} ↗</a>`
       + `<span class="src-feed-meta">${fmt(f.count)}</span></li>`;
}

function inputsCardHTML(c) {
  const recentLabel = {
    agenda: "Recent staff reports", tracker: "Recently added",
    news: "Recent articles", routing: "Recently received",
    inventory: "Sample of inventory",
  }[c.key] || "Recent additions";

  let html = `<section class="src-card src-${esc(c.key)}">`;
  html += `<div class="src-head"><h3>${esc(c.title)}</h3><span class="src-count">${fmt(c.count)}</span></div>`;
  html += `<div class="src-fresh">${esc(c.freshness)}`;
  if (c.detail) html += ` <span class="src-detail">· ${esc(c.detail)}</span>`;
  html += `</div>`;
  html += `<p class="src-blurb">${esc(c.blurb)}</p>`;
  if (c.feeds && c.feeds.length) {
    html += `<div class="src-subhead">Working links (${c.feeds.length})</div>`;
    html += `<ul class="src-feeds">${c.feeds.map(feedItem).join("")}</ul>`;
  }
  if (c.recent && c.recent.length) {
    html += `<div class="src-subhead">${recentLabel}</div>`;
    html += `<ul class="src-recent">${c.recent.map(inputItem).join("")}</ul>`;
  }
  html += `</section>`;
  return html;
}

function renderInputs(d) {
  const intro = document.getElementById("inputs-intro");
  if (intro) intro.textContent =
    `${fmt(d.total)} mapped projects, drawn from five feeds · updated ${d.generated_at}`;
  document.getElementById("inputs-grid").innerHTML = d.cards.map(inputsCardHTML).join("");
}

async function openInputs() {
  const ov = document.getElementById("inputs-overlay");
  ov.classList.add("open");
  ov.setAttribute("aria-hidden", "false");
  if (!inputsData) {
    try {
      const res = await fetch("data/pipeline_sources.json", { cache: "no-cache" });
      if (!res.ok) throw new Error(res.status);
      inputsData = await res.json();
      renderInputs(inputsData);
    } catch (e) {
      document.getElementById("inputs-grid").innerHTML =
        `<div class="metric-loading">Couldn't load the inputs summary.</div>`;
    }
  }
}

function closeInputs() {
  const ov = document.getElementById("inputs-overlay");
  ov.classList.remove("open");
  ov.setAttribute("aria-hidden", "true");
}

document.getElementById("inputs-btn").addEventListener("click", openInputs);
document.getElementById("inputs-close").addEventListener("click", closeInputs);
document.getElementById("inputs-overlay").addEventListener("click", (e) => {
  if (e.target.id === "inputs-overlay") closeInputs();   // click the dimmed backdrop
});
document.addEventListener("keydown", (e) => {
  if (e.key !== "Escape") return;
  if (document.getElementById("inputs-overlay").classList.contains("open")) {
    closeInputs();
  } else if (Editor.editing && !Editor.busy) {
    Editor.cancel();   // leave edit-parcel mode, back to the project detail view
  } else if (document.getElementById("detail").classList.contains("open")) {
    closeDetail();     // a second Escape (or when just viewing) closes the sidebar
  }
});

// ============================================================================
// LOCAL PARCEL EDITOR
// ----------------------------------------------------------------------------
// Reassign a project to the correct parcel(s) by clicking them on the map. ONLY
// active when tools/edit_server.py is serving the site (it answers /api/health);
// the public GitHub Pages build has no /api backend, so this stays fully dormant
// there — no toolbar, no behaviour change. Edits write to the live DB and re-
// export the GeoJSON locally; publishing still means a separate, gated deploy.
// ============================================================================
const EMPTY_FC = { type: "FeatureCollection", features: [] };

const Editor = {
  available: false,   // backend present (only true under edit_server.py)
  editing: false,     // a project is open in parcel-pick mode
  busy: false,        // an async call is in flight (ignore stray clicks)
  pid: null,
  name: "",
  county: "",
  selection: [],      // [{key, apn, geometry, area_acres}]
  ctx: null,          // detailCtx snapshot, so Cancel can restore the detail view

  async init() {
    try {
      const r = await fetch("/api/health", { cache: "no-store" });
      if (!r.ok) return;
      const j = await r.json();
      if (!j || !j.editor) return;
    } catch (_) { return; }   // no backend → public site, stay hidden
    this.available = true;
  },

  // ---- footer shown at the bottom of every project's detail sidebar ----
  footerHTML() {
    return `<div class="ed-foot">` +
      `<button class="ed-btn" data-ed-act="edit">✎ Edit parcels</button>` +
      `<button class="ed-btn ed-foot-del" data-ed-act="delete">Delete project</button>` +
      `</div>`;
  },

  // ---- map click router (only fires while a project is open in edit mode) ----
  onMapClick(e) {
    if (!this.editing || this.busy) return;
    this.pickParcelAt(e.lngLat);
  },

  ensureLayers() {
    if (map.getSource("edit-selection")) return;
    map.addSource("edit-window", { type: "geojson", data: EMPTY_FC });
    map.addSource("edit-current", { type: "geojson", data: EMPTY_FC });
    map.addSource("edit-selection", { type: "geojson", data: EMPTY_FC });
    // all loaded parcels: faint blue outlines so every clickable parcel is visible
    map.addLayer({
      id: "edit-window-line", type: "line", source: "edit-window",
      paint: { "line-color": "#9ad7ff", "line-opacity": 0.3, "line-width": 0.7 },
    });
    // current footprint: white dashed reference outline of what we're replacing
    map.addLayer({
      id: "edit-current-line", type: "line", source: "edit-current",
      paint: { "line-color": "#ffffff", "line-opacity": 0.75,
               "line-width": 1.6, "line-dasharray": [2, 2] },
    });
    // chosen parcels: bright cyan highlight, drawn on top of everything
    map.addLayer({
      id: "edit-selection-fill", type: "fill", source: "edit-selection",
      paint: { "fill-color": "#00e5ff", "fill-opacity": 0.35 },
    });
    map.addLayer({
      id: "edit-selection-line", type: "line", source: "edit-selection",
      paint: { "line-color": "#00e5ff", "line-opacity": 0.95, "line-width": 2.2 },
    });
  },

  // "Edit parcels" in the sidebar → enter parcel-pick mode for the open project.
  async beginEdit() {
    if (!detailCtx || this.busy) return;
    const p = detailCtx.p;
    const pid = Number(p.project_id);
    const ll = detailCtx.lngLat;
    if (!pid || !ll) {
      setStatus("Couldn't locate this project on the map to edit it.");
      return;
    }
    this.ensureLayers();
    this.busy = true;
    this.editing = true;
    this.pid = pid;
    this.name = p.project_name || "(unnamed project)";
    this.county = p.county || "";
    this.selection = [];
    this.ctx = detailCtx;
    document.body.classList.add("editing-mode");
    this.setCurrent(null);
    this.renderSelection();
    this.renderEditPanel();
    setStatus(`Loading parcels near <b>${esc(this.name)}</b>&hellip;`);
    try {
      const res = await this.apiPost("/api/begin_edit",
        { pid, lon: ll.lng, lat: ll.lat });
      this.county = res.county || this.county;
      this.setCurrent(res.current_geom || null);
      await this.loadWindowOutlines();
      this.busy = false;
      this.renderEditPanel();
      if (!res.parcels_loaded) {
        setStatus("No parcels loaded right here — pan to the project and click " +
                  "<b>Reload parcels here</b>.");
      } else {
        setStatus(`Editing <b>${esc(this.name)}</b> — click the correct ` +
                  `parcel(s), then <b>Save footprint</b>. ` +
                  `(${fmt(res.parcels_loaded)} parcels shown.)`);
      }
    } catch (err) {
      this.busy = false;
      this.endEdit();
      if (this.ctx) openDetail(this.ctx.p, this.ctx.lngLat);
      setStatus(`Couldn't load parcels: ${esc(String(err.message || err))}`);
    }
  },

  // Outline every parcel in the loaded window so the user sees what's clickable.
  async loadWindowOutlines() {
    try {
      const fc = await this.apiGet("/api/window_parcels");
      if (map.getSource("edit-window")) map.getSource("edit-window").setData(fc);
    } catch (_) { /* outlines are a nicety; picking still works without them */ }
  },

  async pickParcelAt(lngLat) {
    this.busy = true;
    try {
      const res = await this.apiGet(
        `/api/parcel_at?lat=${lngLat.lat}&lon=${lngLat.lng}`);
      this.busy = false;
      if (!res.found) {
        setStatus("No parcel there. If it's outside the loaded area, pan to it " +
                  "and click <b>Reload parcels here</b>.");
        return;
      }
      const key = res.apn ? "apn:" + res.apn : "g:" + JSON.stringify(res.geometry);
      const i = this.selection.findIndex((s) => s.key === key);
      if (i >= 0) this.selection.splice(i, 1);
      else this.selection.push({ key, apn: res.apn,
                                 geometry: res.geometry, area_acres: res.area_acres });
      this.renderSelection();
      this.renderEditPanel();
    } catch (err) {
      this.busy = false;
      setStatus(`Parcel lookup failed: ${esc(String(err.message || err))}`);
    }
  },

  async reloadHere() {
    if (!this.editing || this.busy) return;
    this.busy = true;
    const c = map.getCenter();
    setStatus("Loading parcels in view&hellip;");
    try {
      const res = await this.apiPost("/api/begin_edit",
        { pid: this.pid, lon: c.lng, lat: c.lat, force: true });
      await this.loadWindowOutlines();
      this.busy = false;
      setStatus(`Parcels reloaded (${fmt(res.parcels_loaded)}). Keep clicking ` +
                `the correct parcel(s).`);
    } catch (err) {
      this.busy = false;
      setStatus(`Reload failed: ${esc(String(err.message || err))}`);
    }
  },

  async save() {
    if (!this.editing || this.busy) return;
    if (!this.selection.length) {
      setStatus("Select at least one parcel first, or use <b>Remove footprint</b>.");
      return;
    }
    this.busy = true;
    setStatus(`Saving <b>${esc(this.name)}</b>&hellip;`);
    try {
      const res = await this.apiPost("/api/reassign",
        { pid: this.pid, geometries: this.selection.map((s) => s.geometry) });
      const pid = this.pid, nm = this.name;
      this.endEdit();
      await this.refreshData();
      this.reopenDetail(pid);
      setStatus(`Saved <b>${esc(nm)}</b> — ${res.parcel_count} parcel(s), ` +
                `${res.area_acres} ac. Remaining units updated.`);
    } catch (err) {
      this.busy = false;
      setStatus(`Save failed: ${esc(String(err.message || err))}`);
    }
  },

  async clear() {
    if (!this.editing || this.busy) return;
    if (!window.confirm(
        `Remove the parcel footprint for "${this.name}"?\n` +
        `It will revert to a dot at its geocoded address.`)) return;
    this.busy = true;
    setStatus(`Removing footprint for <b>${esc(this.name)}</b>&hellip;`);
    try {
      const pid = this.pid, nm = this.name;
      await this.apiPost("/api/clear_geom", { pid });
      this.endEdit();
      await this.refreshData();
      this.reopenDetail(pid);
      setStatus(`Removed footprint for <b>${esc(nm)}</b>.`);
    } catch (err) {
      this.busy = false;
      setStatus(`Remove failed: ${esc(String(err.message || err))}`);
    }
  },

  // "Delete project" → permanent, irreversible hard delete (double-confirmed).
  async deleteProject() {
    if (!detailCtx || this.busy) return;
    const p = detailCtx.p;
    const pid = Number(p.project_id);
    const nm = p.project_name || "(unnamed project)";
    if (!pid) return;
    if (!window.confirm(
        `Permanently delete "${nm}" from the database?\n\n` +
        `This removes the project, its parcel footprint, and its version ` +
        `history. It CANNOT be undone.`)) return;
    if (!window.confirm(`Last check — "${nm}" will be gone for good. Delete it?`))
      return;
    this.busy = true;
    setStatus(`Deleting <b>${esc(nm)}</b>&hellip;`);
    try {
      await this.apiPost("/api/delete_project", { pid });
      this.endEdit();
      await this.refreshData();
      closeDetail();
      setStatus(`Deleted <b>${esc(nm)}</b> from the database.`);
    } catch (err) {
      this.busy = false;
      setStatus(`Delete failed: ${esc(String(err.message || err))}`);
    }
  },

  // Cancel parcel editing and return to the project's normal detail view.
  cancel() {
    if (!this.editing) return;
    const ctx = this.ctx;
    this.endEdit();
    if (ctx) openDetail(ctx.p, ctx.lngLat);
    setStatus(null);
  },

  // Tear down edit state + clear all edit overlays from the map.
  endEdit() {
    this.editing = false;
    this.busy = false;
    this.pid = null;
    this.selection = [];
    this.ctx = null;
    document.body.classList.remove("editing-mode");
    for (const s of ["edit-window", "edit-current", "edit-selection"]) {
      if (map.getSource(s)) map.getSource(s).setData(EMPTY_FC);
    }
  },

  setCurrent(geom) {
    if (!map.getSource("edit-current")) return;
    map.getSource("edit-current").setData(
      geom ? { type: "FeatureCollection",
               features: [{ type: "Feature", geometry: geom, properties: {} }] }
           : EMPTY_FC);
  },

  renderSelection() {
    if (!map.getSource("edit-selection")) return;
    map.getSource("edit-selection").setData({
      type: "FeatureCollection",
      features: this.selection.map((s) => ({
        type: "Feature", geometry: s.geometry, properties: {} })),
    });
  },

  // Render the parcel-pick controls into the detail sidebar body.
  renderEditPanel() {
    const body = document.getElementById("detail-body");
    if (!body) return;
    const n = this.selection.length;
    const ac = this.selection.reduce((t, s) => t + (s.area_acres || 0), 0);
    body.innerHTML =
      `<span class="detail-chip" style="background:#00b3c6">Editing parcels</span>` +
      `<div class="detail-name">${esc(this.name)}</div>` +
      `<div class="detail-sub">${esc(this.county ? this.county + " County" : "")}</div>` +
      `<div class="ed-stats">${n} parcel${n === 1 ? "" : "s"} selected` +
        (n ? ` &middot; ${ac.toFixed(2)} ac` : "") + `</div>` +
      `<div class="ed-actions">` +
        `<button class="ed-act ed-save" data-ed-act="save"${n ? "" : " disabled"}>Save footprint</button>` +
        `<button class="ed-act" data-ed-act="reload">Reload parcels here</button>` +
        `<button class="ed-act ed-danger" data-ed-act="clearfoot">Remove footprint</button>` +
        `<button class="ed-act" data-ed-act="cancel">Cancel</button>` +
      `</div>` +
      `<div class="ed-hint">Click parcels on the map to add/remove them.<br>` +
        `<span style="color:#9ad7ff">Faint blue</span> = all parcels &middot; ` +
        `<span style="color:#fff">white dashed</span> = current footprint &middot; ` +
        `<span style="color:#00e5ff">cyan</span> = your selection.</div>`;
  },

  // Re-open the sidebar for a project from the freshly re-exported data, so the
  // user sees the new footprint/units immediately after a save or footprint clear.
  reopenDetail(pid) {
    const src = map.getSource("projects");
    const data = src && src._data;
    const f = data && (data.features || []).find(
      (x) => Number(x.properties.project_id) === Number(pid));
    if (f) openDetail(f.properties, pointOf(f, null));
  },

  async refreshData() {
    const [pj, pc] = await Promise.all([
      fetch("data/pipeline.geojson", { cache: "no-cache" }).then((r) => r.json()),
      fetch("data/pipeline_parcels.geojson", { cache: "no-cache" }).then((r) => r.json()),
    ]);
    if (map.getSource("projects")) map.getSource("projects").setData(pj);
    if (map.getSource("parcels")) map.getSource("parcels").setData(pc);
    if (pj.metrics) renderMetrics(pj.metrics);
    inputsData = null;   // force the Inputs dashboard to re-fetch next open
  },

  async apiGet(path) {
    const r = await fetch(path, { cache: "no-store" });
    if (!r.ok) throw new Error(r.status);
    return r.json();
  },
  async apiPost(path, body) {
    const r = await fetch(path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!r.ok) {
      let msg;
      try { msg = (await r.json()).error; } catch (_) { /* ignore */ }
      throw new Error(msg || r.status);
    }
    return r.json();
  },
};

Editor.init();
